README.rst, bower.json, crime_data/app.py, crime_data/static/crime-data-api-swagger.yaml, package.json, requirements/prod.txt
Adds a very basic swagger configuration file and some build steps to install `swagger-ui`. I didn't even cover all of the endpoints, or the values that they take and also the fact that all requests require an API key.
I also replaced `bower.json` with `package.json` as it is [18F's policy not to use `bower`](https://pages.18f.gov/frontend/#bower).
=> Add basic Swagger UI definition

crime_data/resources/helpers.py, manifest.yml
We use `autopilot` for continuous deploys and as a result env variables must be set in either the `manifest.yml` file or in a user provided service. We need to keep sensitive information like the api key in a cloud.gov service.
* Updates the manifest to bind the service to each new application.
* Parses the `VCAP_SERVICES` environment variable to get the `API_KEY`
=> Use a "user provided service" to store sensitive information like api keys

crime_data/settings.py
I think this variable is used by Flask to support subdomains ([relevant Flask docs](http://flask.pocoo.org/docs/0.11/config/#builtin-configuration-values)) but it is causing our app to not run properly at all, either locally or on cloud.gov
I've gone ahead and removed it, pushed to cloud.gov in a temp app and it seems to have worked.
=> Remove SERVER_NAME from prod config settings

crime_data/app.py, crime_data/common/base.py, crime_data/common/models.py, crime_data/public/forms.py, crime_data/public/views.py, crime_data/resources/helpers.py, crime_data/resources/incidents.py, crime_data/user/models.py, tests/functional/test_incidents.py
- API results include metadata with pagination info, even for /count/ endpoint formed by SQLAlchemy Core query
- YAPF and iSort applied for consistent formatting
=> pagination for /count/

crime_data/common/marshmallow_schemas.py
Namespace Collision issue:
from marshmallow import Schema, fields
...
**fields** = **fields**.String()
if os.getenv('VCAP_APPLICATION'):
api_key = **fields**.String(...      # Overwriting module with String.
...
=> Renamed import to avoid namespace collision

README.md
We reached a point where we wanted to actually check in our javascript dependencies to the repository so we can modify them. I forgot to remove the step from the README
=> Remove npm steps from project setup

crime_data/common/base.py, crime_data/common/cdemodels.py, crime_data/common/marshmallow_schemas.py, crime_data/resources/incidents.py, requirements/prod.txt
This is the initial stab at csv support. We still need to add support for file header settings, and file download. Right now it just outputs text.
usage:
/incidents/?output=csv
=> Added initial incidents endpoint csv support

crime_data/common/base.py, crime_data/common/cdemodels.py, crime_data/resources/incidents.py
flask_sqlalchemy's built-in paginator has been failing badly (giving drastically low counts) for the complex queries beneath `/incidents/` and `/incidents/count/`.  Now counts match those produced with simple handwritten SQL.
=> Fix pagination

.codeclimate.yml
This should also ignore the code in the `static/` directory which comes from outside vendors
=> Add a codeclimate configuration

crime_data/common/base.py, crime_data/common/marshmallow_schemas.py, crime_data/resources/incidents.py
This adds the ability to toggle between seeing one-to-many fields listed out in CSV like:
offenses_0..., offenses_1...., offenses_2,...
and,
offenses (count), ...
with the url attribute: aggregate_many=false/true
=> Added ability to view flattened one-to-many attributes in CSV.

.codeclimate.yml
Want to avoid anaylzing files in the /static/ directory
=> Wrong dir for static in codeclimate.yml

.codeclimate.yml
These were triggering a lot of false positives for the duplication engine since we have a lot of tables with similar structures, so I have disabled the duplication checks for those files
=> Have the duplication engine skip models/schemas

SWAGGER.md, crime_data/app.py, crime_data/common/base.py, crime_data/common/cdemodels.py, crime_data/common/marshmallow_schemas.py, crime_data/resources/agencies.py, crime_data/resources/arrests.py, crime_data/resources/arson.py, crime_data/resources/codes.py, crime_data/resources/incidents.py, crime_data/resources/offenses.py, requirements/prod.txt, tests/functional/test_incidents.py
This is using the [flask-apispec] library. Note that this is not _pretty_ Swagger for developers yet, the basic idea is to give the frontend team something to use so they can play with the API a little before it gets too far into yak-shaving territory. Right now I have the following parts done:
Not all of these need to be done in this sprint and most of these can wait for future sprints, when it's time to be more public-facing
=> Basic Swagger generation from the code

requirements/prod.txt
Since we no longer have users/roles in this application, there is no reason for the requirements to still include Flask form and login libraries.
=> Remove login/form libraries

SWAGGER.md, crime_data/app.py
Looks like the VCAP_SERVICES already have a HTTP_BASIC_USERNAME and HTTP_BASIC_PASSWORD already defined, so use them instead of relying on the user to set it
=> Read the HTTP password and username from VCAP_SERVICES

crime_data/app.py, crime_data/common/cdemodels.py, crime_data/resources/meta.py, tests/functional/test_meta.py
Fixes #198
A call for /meta/incidents/count will return information about the incidents/count API endpoint, mainly what the filter columns you can present to either the main query string or also to the `by` or `fields` arguments in a query string. I don't have them for everything yet, just those functions that use the TableFamily classes and subclasses (so it seems like `offenses` doesn't have this)
Note: this has a functional integration test for the endpoint, but it probably should ideally also have a unit test for the change to the `cdemodels.TableFamily` class. We don't seem to have any unit tests for sub-API-response classes yet though, so we need to add those as another task I think.
=> Add a /meta/* endpoint to the API

crime_data/common/base.py
Added another branch to run full count query if no exception was thrown, AND count_estimated is not required
=> Add logic to run full count query when estimates aren't required.

crime_data/resources/meta.py, tests/functional/test_meta.py
This way something like `meta/incidents/` works
=> Meta endpoint ignores trailing slashes

crime_data/app.py
I think this code is fine, so I added a #nosec to ignore. I am not sure why `bandit` did not fail when run on the PR, but I will have to investigate. This might mean a change to the circle config
=> Bandit was triggering on New Relic error handling

crime_data/app.py, crime_data/common/cdemodels.py, crime_data/common/marshmallow_schemas.py, crime_data/common/models.py, crime_data/resources/geo.py, tests/conftest.py, tests/factories.py, tests/functional/test_geo.py, tests/unit/test_cdemodels.py
Fixes #279 
This will be code to return demographic information for states (called by postal code) or counties (called by FIPS code) from the database.
I did this PR as an experiment of adding methods to the base SQLAlchemy classes by using new CdeRefState and CdeRefCounty classes. This way if the `models.py` file is regenerated, that functionality is supposed to still be there. 
I do wonder though if we should consider some way to monkey patch the existing classes rather than defining new wrappers, because there was one point where SqlAlchemy was confused and didn't know whether to instantiate a RefCounty or CdeRefCounty object on a back reference. The idea would be to not let people import from `crime_data.common.models`. Instead everybody would import from `crime_data.common.cdemodels` …
=> Add state and county demographics endpoints

.codeclimate.yml
It's a good aspiration, but the pep8 checking is turning into a real hassle for our process at the moment. Can reenable when we have more capacity down the road.
=> Disable pep8 checking for CodeClimate

requirements/prod.txt
The swagger documentation was failing with
> TypeError: 'bool' object is not iterable
The issue seems to be related to new versions of Marshmallow and APIspec that were released in January and that flask-apispec was not pinned to a specific version. Pinned both to an older version which resolved it.
=> Fix for Swagger documentation crash

api_support_notes.md, crime_data/app.py
Since we are in ATO review now, it is okay to remove the HTTP Auth protection around the /swagger/ and /swagger-ui/ endpoints
=> Remove HTTP auth protection for Swagger

crime_data/app.py, crime_data/common/cdemodels.py, crime_data/resources/cargo_theft.py, crime_data/resources/hate_crime.py, crime_data/resources/offenders.py, crime_data/resources/offenses.py, crime_data/resources/victims.py, tests/functional/test_cargo_theft.py, tests/functional/test_hate_crime.py, tests/functional/test_offenders.py, tests/functional/test_offense_cargo_theft.py, tests/functional/test_offense_hate_crime.py, tests/functional/test_offense_victims.py, tests/functional/test_offenses.py, tests/functional/test_victims.py, tests/unit/test_cdemodels.py
To avoid confusion and be consistent with other API endpoints, I changed the various count_view API endpoints to also accept a state_abbr (postal code) instead of a state_id, if you'd prefer. So a query like `victims/count/states/WY` works now
=> Count views should also accept state postal codes

crime_data/app.py, crime_data/common/base.py, crime_data/common/cdemodels.py, crime_data/common/marshmallow_schemas.py, crime_data/resources/cargo_theft.py, crime_data/resources/hate_crime.py, crime_data/resources/incidents.py, crime_data/resources/offenders.py, crime_data/resources/offenses.py, crime_data/resources/victims.py, requirements/prod.txt, tests/functional/test_incidents.py, tests/functional/test_offense_cargo_theft.py, tests/functional/test_offense_hate_crime.py, tests/functional/test_offense_offenders.py, tests/functional/test_offense_victims.py, tests/unit/test_cdemodels.py
The idea of this is that the frontend API should only have to pass a single universal argument for offenses and it is mapped to the appropriate RET A or NIBRS offenses in the backend. So, this call `/incidents/count/?explorer_offense=murder` is actually mapped to use the RET A offense code we are displaying for murder. Similarly, it can be used with the NIBRS endpoints as well, but I still have to wire that up.
=> Offense mapping

crime_data/common/cdemodels.py
Fixes #368 
Guidance from the FBI is that we should only use pe_employee_data fields where reported_flag='Y' to compute police staffing
=> Police employee count should only be for reporting agencies

crime_data/common/cdemodels.py, crime_data/resources/geo.py, tests/unit/test_cdemodels.py
Fixes #366
For some reason, it's sharing the cached object across all instances. Python, I don't understand you sometimes.
=> Disabling caching for the CdeRefState

crime_data/app.py
These endpoints hit very large tables, and necessitate full sequential scans (in their current implementation). As a result, they blow right past the per request memory limit (query work_mem), and go to swap. Eventually they time out, and bring down the entire server along with it (along with leaving zombie  queries spinning on the production DB). They should be disabled.
Satisfies #337
/cryptictone
=> Disable Arson, Arrests, and Incidents details endpoints

crime_data/resources/arson.py, dba/after_load.sh, dba/after_load/add_arson_to_reta_summary.sql, dba/after_load/create_reta_summary.sql, dba/after_load/reta_summary.sh, tests/functional/test_arrests.py, tests/functional/test_arson.py, tests/functional/test_incidents.py, tests/unit/test_newmodels.py
**Work in progress: do not merge yet**
Fixes #364
Arson is one of the Property crimes we have in the explorer, but Arson data is kept separate from the Return A table that is used for state and national trends. Since we have created our own denormalized view of the Return A tables named `reta_month_offense_subcat_summary`, we can add arson statistics to it. This PR will be done when the following stuff is in there:
I'm not sure if the incrementing could be done correctly as part of the insertion process for #1. Postgres does have a `INSERT ON CONFLICT` directive for handling conflicts, but that might rely on the table having unique keys that it might not have right now.
=> Add Arson groupings to the reta_month_offense_subcat_summary table

crime_data/common/cdemodels.py, crime_data/common/marshmallow_schemas.py
See https://github.com/18F/crime-data-explorer/issues/125 for details.
This adds a `participation` key to the object returned by the `/geo/states/<state_id>` endpoint. We can probably remove the separate `/geo/states/<state_id>/participation` endpoint once this is merged.
=> Add participation data to the /geo/states/ endpoint

crime_data/common/marshmallow_schemas.py, crime_data/common/newmodels.py, dba/after_load/participation_table.sql, tests/unit/test_newmodels.py
Fixes #384 
The nibrs_month table tells us if an agency has filed a NIBRS report in a given month (reta_month covers both agencies that filed RET A reports, those that filed both and those that filed only NIBRS reports that were then converted over). Since we display some statistics from NIBRS data, it might be good to show those specific rates
=> Add NIBRS-specific counts to participation tables

crime_data/app.py, crime_data/common/cdemodels.py, crime_data/resources/offenses.py, dba/after_load/mat-views/aggregate-views.sql, tests/functional/test_offense_by_offense_types.py, tests/unit/test_cdemodels.py
Add a new `.../offenses` API endpoint on the `/offenses/count` method so you can do things like
'/offenses/count/national/location_name/offenses` (I know it's not great, but we can revise URLs later).
=> Explorer offense should be argument to offense count view

crime_data/common/base.py, crime_data/resources/agencies.py, crime_data/resources/geo.py
Fixes https://github.com/18F/crime-data-explorer/issues/312
This does a few things:
1. Add support to pass an `output=csv` argument to the `geo/states/<state_id>/participation` endpoint
2. The `/agencies/participation` endpoint also accepts a `year=1991` or ranged `year=1991-2001` arguments
=> A few csv fixes

crime_data/common/base.py, crime_data/common/marshmallow_schemas.py, crime_data/settings.py
I wanted to make it so I could actually order the columns of the CSVs to match the ordering in Marshmallow, and this seems to work?
I hope this doesn't break anything else but this is the fun of not having great test coverage for base class methods like this
=> Fixing it so CSVs obey ordered=True from Marshmallow

crime_data/app.py, crime_data/common/cdemodels.py, crime_data/common/marshmallow_schemas.py, crime_data/common/newmodels.py, crime_data/resources/geo.py, crime_data/resources/participation.py, dba/after_load/participation_table.sql, tests/functional/test_participation.py, tests/unit/test_cdemodels.py, tests/unit/test_newmodels.py
This pull request fixes two things:
1. Changes total populations for states and counties to be a sum of agency population instead of county population.
2. Adds `state_name` and `county_name` to the `cde_participation_rate` table so I don't need to join because SqlAlchemy is terrible.
This adds a new endpoint at `/participation/national`
=> National participation endpoint

crime_data/app.py, crime_data/resources/agencies.py
Fixes the CSV to match what is in https://github.com/18F/crime-data-explorer/issues/312#issuecomment-284599623
I also changed it to follow the same convention for specifying year ranges with `year>=2004&year<=2014` to have parity with other API methods. This will change how you call it @jeremiak
=> Reorder the columns in the agency participation CSV

CHANGELOG.md
@harrisj and @cacraig, please let me know if I missed anything!
I generated the change log from reviewing the issues that were closed over the past two weeks and this commit compare: https://github.com/18F/crime-data-api/compare/c04591e2514c3bc223ae6c88e318adac1d8a1acb...e99e7eb2de2a7b46c64cc1f36906fc809d22e963
I didn't want to tag the commit yet in case I missed something, so once I get the 👍 from ya'll I will tag the commit with `v2017-03-15`.
=> Add CHANGELOG for 2017-03-15 release

crime_data/common/base.py, crime_data/common/marshmallow_schemas.py, tests/functional/test_authentication.py
Fixes #434 
This is necessary to prevent a situation where api.data.gov might accidentally reveal the API key
=> Allow authentication via HTTP X-API-KEY header instead

crime_data/app.py, crime_data/common/base.py, crime_data/common/cdemodels.py, crime_data/resources/cargo_theft.py, crime_data/resources/hate_crime.py, crime_data/resources/offenders.py, crime_data/resources/offenses.py, crime_data/resources/victims.py, tests/functional/test_offense_by_offense_types.py, tests/functional/test_offense_offenders.py
FINALLY. SOMETHING THAT IS NOT A SQL SCRIPT.
- Modified swagger generation to specify state_abbr case insensitive instead of state_id @harrisj    This will probably need to change in your swagger work.  
- state_id still works, so it can be either state_id or abbr.  
- Added route for mapping /incidents/count to /counts. 
- Added page cap for paginated requests.  
Addresses: #281 ,  #336,  and #403 .
=> Api usability

crime_data/app.py, crime_data/resources/agencies.py, crime_data/resources/geo.py, crime_data/resources/participation.py, crime_data/static/swagger.json, tests/functional/test_geo.py, tests/functional/test_participation.py
Fixing some issues around participation noted in #406. Also, noticed some missing tests.
This still keeps the old API endpoints for compatibility, but we will want to remove those eventually.
=> Clean up participation endpoints

crime_data/common/base.py, crime_data/common/cdemodels.py
Time to axe these relics. Feels good.
- Removed some unused code. Hopefully clear up a little confusion when grok-ing this code.
=> Removed some unused code

dba/after_load.sh, dba/after_load/denorm-agencies.sql, dba/after_load/flatten-covered-by.sql
Fixes #458 
This has a recursive select that might be a bit crazy?
If agency A is covered by B and B is covered by C, this will store C as covering both A and B
=> Add ref_agency_covered_by_flat table

crime_data/common/base.py, crime_data/common/cdemodels.py
The problem: We are getting a bunch of "Idle in Transaction" queries in the DB because something is causing requests to die/timeout. The connection is being left open without issuing a commit, or an END for the transaction. - This concerns mostly anything querying against the reta_month summary tables.
This is the simplest way to handle this is to close off every connection at the end of a transaction. If this doesn't work then we may need to disable the SQLAlchemy connection pooling.
=> Close connections always.

dba/after_load/create_reta_summary.sql, dba/after_load/participation_table.sql, tests/functional/test_authentication.py, tests/unit/test_cdemodels.py, tests/unit/test_newmodels.py
Because we will need to have 12-month participation, the sample data was too incomplete for some tests. So I have added records from 2014 in Rhode Island to the following tables:
* reta_month
* ref_agency
* ref_agency_county
* reta_offense
* reta_offense_subcat
* reta_month_offense_subcat
* arson_month
* arson_month_by_subcat
* arson_subcat
* pe_employee_data
So, get yourself a nice coffee milk and enjoy the world of 2014 Rhode Island crime
=> Add sample data for Rhode Island 2014 crime

crime_data/common/newmodels.py
Well this is embarrassing.  - I left one tab too many. The query for counties doesn't execute the subquery for the county info if no year is supplied.
=> One more fix for RETA agency api.

crime_data/app.py, crime_data/common/newmodels.py, crime_data/resources/incidents.py, crime_data/static/swagger.json
This PR adds CSV output ability on the agency level sums endpoints. Also fixes issue with ORI specific requests.  
Added API's for getting offense level counts by ORI, and county fips.
=> Added CSV output ability. Fixed ORI only requests.

crime_data/common/marshmallow_schemas.py, crime_data/common/newmodels.py, dba/after_load/create_reta_agency_summary.sql, dba/after_load/update.sql, update.sh
Okay 
- So this might be a good middle ground. I reworked the offense count table to group/sum the results.
- I also fixed the agency_sums to correctly sum up the sub offense counts.
One thing I don't like: Sub-offense counts return an object for each (sub-offense, agency, year) which means that pagination could cut off parts of the response. This shouldn't be an issue when requesting one agency at a time. But ideally we would return the full payload in one object. ie.
[
{
ori:
year:
suboffense_count1:
suboffense_count2:
suboffense_countN:
}, ...
]
buuuut. It's actually a pretty tough thing to tackle - I'd rather wait to see if it's worth doing before going down this road.
=> Reta agency API

.cfignore
I just realized we never had a .cfignore for this project which means that all sorts of files are being deployed that don't need to be pushed to the server like the test DB SQL or the tests directory
=> Add a .cfignore to the project

crime_data/common/cdemodels.py, dba/after_load.sh, dba/after_load/mat-views/cargo-theft.sql, dba/after_load/mat-views/offender-offenses.sql, dba/after_load/years.sql
This fixes some major performance issues in production with the NIBRS API's. The indexes and such are already live.
=> Nibrs agency api

crime_data/common/base.py, crime_data/common/newmodels.py, crime_data/resources/incidents.py
Fixes #517, but the front end will have to do the grouping for now. In the long run, I think we should make a version of the agencies_sums_view table with some grouping like the reta_month_offense_subcat_summary table.
=> Suboffense query takes explorer_offense argument

dba/after_load/denorm-agencies.sql, tests/unit/test_newmodels.py
Fixes #501. This is already fixed in production, but this PR updates the test data and tests...
=> Use reta_month to get current_year for cde_agencies

crime_data/common/base.py
Fixes https://github.com/18F/crime-data-explorer/issues/129
It was suggested on a recent call that our page for rape should also map to the NIBRS offenses of Incest and Sexual Assault With An Object, so... 
(this database will make you sad sometimes)
=> Widen NIBRS rape mapping

Procfile, crime_data/common/base.py, crime_data/common/models.py, crime_data/extensions.py, dba/after_load/mat-views/offender-offenses.sql
API seems to still be using db connection pooling. I think this may fix it.  
(1) Explicitly release connections on thrown exceptions.
(2) Changed imported db class to correct one in models.py
=> API still using a pool. Stahp.

crime_data/app.py, crime_data/common/marshmallow_schemas.py, crime_data/common/newmodels.py, crime_data/resources/arson.py, crime_data/static/swagger.json, dba/after_load.sh, dba/after_load/create_arson_table.sql, tests/functional/test_arson.py
Fixes #552.
I still need to build the table in production, but that shouldn't take too long
=> Bring back arson endpoint

crime_data/common/base.py, dba/after_load/create_reta_agency_summary.sql
Fixes #565 
The DB changes are already in production, and we now match the Crime in the United States numbers for violent offenses (they use actual count, we use reported though so we're slightly higher). To make the aggravated assault numbers match, you must merge this.
=> Aggravated assault should not include simple assault

crime_data/common/newmodels.py, crime_data/static/swagger.json, dba/after_load/denorm-agencies.sql
Fixes #569
This is a measure of how many times in the past decade of SRS reports, the given agency has reported 12 months of data. This is relative to the most recent year of SRS reports not the current calendar year (so for instance, right now we only have 2014 data so it's counting the years 2005-2014).
This column is already in the production DB. Just needs this PR merged for it to appear.
=> Add past_10_years_reported to cde_agencies

dba/after_load/mat-views/victim.sql
Fixed victim_count_ori query. Currently selects from non-existent table.
=> Fixed victim_count_ori query

crime_data/app.py, crime_data/resources/arson.py, crime_data/resources/cargo_theft.py, crime_data/resources/hate_crime.py, crime_data/resources/human_traffic.py, crime_data/resources/incidents.py, crime_data/resources/offenders.py, crime_data/resources/offenses.py, crime_data/resources/participation.py, crime_data/resources/victims.py
Reverts 18F/crime-data-api#587
Right now this is crashing CSV downloads of API endpoints. I have a more involved fix to restore it, but best to save that for the next sprint
=> Revert "Set Surrogate-Control Header to cache responses for an hour"

manifests/production.yml, manifests/staging.yml
Change URLs such that `crime-data-api` will be for the production (and rename manifest from `demo.yml` for clarity) and `crime-data-api-master` will be used for the continuously deployed
=> Use -api-master URL for master branch

circle.yml
The manifest file was deploying our master app to the old URL and therefore removing the production instance. Changes so that the app is deployed with the proper app name
=> Use master app name

crime_data/common/newmodels.py, crime_data/static/swagger.json, dba/after_load/denorm-agencies.sql
Fixes https://github.com/18F/crime-data-frontend/issues/732
This adds a new column `current_nibrs_start_year` to the agencies table that lists the first year of the current reporting run that an agency started reporting NIBRS data. Some sample situations and what this field would be
|Scenario|Current NIBRS Start Year|
|-|-|
|Agencry reported 1991 - |1991|
|Agency reported NIBRS 1991-1992, 2007-|2007|
|Agency never reported NIBRS|NULL|
|Agency reported 2006, 2008, 2010-2014|2010|
|Agency reported 2007-2010 (abandoned after)|2007|
It's not perfect, but it lets you at least set the start year for the NIBRS visualizations. Note that some agencies have been reporting NIBRS continuously since the early 90s
Also, fixes https://github.com/18F/crime-data-explorer/issues/252
=> Add nibrs_start_year to cde agencies

circle.yml
Removing something I left in when I copied over these instructions from the front end. It looks identical, except for the manifest and app name used, to the master deployment now
=> Remove node build step
