crime_data/resources/helpers.py
We were improperly accessing the API_KEY value for the auth check, but now we're not! :)
=> Use API KEY from user provided service

crime_data/app.py, crime_data/common/base.py, crime_data/common/cdemodels.py, crime_data/resources/agencies.py, tests/functional/test_agencies.py
This is a WIP.
- Added agencies/nibrs/count endpoint (no filtering yet).
- Extended models.py to encompass all CDE specific models & business logic. 
Would like a quick review. Probably best to merge before it gets too big.
=> Agencies endpoint

crime_data/common/cdemodels.py, crime_data/common/marshmallow_schemas.py
Correct minor error currently keeping production down.
=> Completed renaming of fields to marsh_fields

crime_data/app.py, crime_data/common/cdemodels.py, crime_data/common/marshmallow_schemas.py, crime_data/resources/offenses.py, tests/functional/test_offenses.py
Future improvements should maybe include correlations to
NibrsOffenseType.offense_code, but those correlations are not
actually in the database.
=> New /offenses/ endpoint with hierarchy of Return A (Summary) categories

crime_data/common/base.py, crime_data/common/marshmallow_schemas.py, crime_data/resources/incidents.py, crime_data/static/swagger.json, requirements/prod.txt, tests/functional/test_incidents.py
In debug mode (dev or test), pass `?tuning=1` to get a report on SQL executed instead of the JSON
=> Display a sqltap analysis when `tuning=1` passed as argument

crime_data/common/base.py, crime_data/common/cdemodels.py, tests/functional/test_incidents.py
Supports filtering for any of a comma-separated list of values, like
`/incidents/?victim.race_code=A,P`
=> Multi value filters

crime_data/common/base.py, crime_data/common/cdemodels.py, crime_data/resources/incidents.py, tests/functional/test_incidents.py
Moved application of DISTINCT so that it wouldn't ruin filtering.
=> Correcting naming bug

crime_data/common/cdemodels.py, crime_data/common/marshmallow_schemas.py, crime_data/common/models.py, crime_data/resources/incidents.py, tests/functional/test_incidents.py
Adds the fields to both the output, and filtering according to #87.
Resolves #87
=> Add fields to API output & filtering mechanism.

circle.yml, crime_data/settings.py
=> Modifying the CircleCI to load/use DB schema

autoapp.py
This is useful for seeing what queries have been run by your app when you go to http://localhost:5000/__sqltap__
=> Development mode can see /__sqltap__ endpoint

README.md
Fixes #24, but it looks like someone else had already added badges for CI and CodeClimate GPA
=> Add test coverage to README

crime_data/common/base.py
PostgreSQL won't continue after a failed query without a rollback.
=> Log and rollback after failing to fast-count rows

crime_data/app.py, crime_data/extensions.py, crime_data/settings.py
I broke things in #189 when I forgot to remove where those libraries were imported. This worked locally for me because I wasn't keeping my virtualenv minimal, but it was breaking deploys.
=> Got a bit too zealous removing some libraries

crime_data/common/base.py
Small fix to use full count query when the estimated count is below <1000 results.  
Addresses #197
=> Fallback to full count when result set is small

crime_data/common/marshmallow_schemas.py, crime_data/settings.py, dba/refresh_production_dba_instructions.md, dba/scrub_private_for_dev.sql, dba/scrub_private_for_prod.sql
=> NULLS out fields that could contain sensitive info & omits from output

crime_data/common/marshmallow_schemas.py
I noticed these when I was looking at another bug. These are my bad, sorry.
=> Fix two small Marshmallow schema errors

crime_data/common/cdemodels.py
Another tiny pull request. This statement is being triggered during pytest. Is this something that is never supposed to happen? Should I be figuring out why this _is_ happening during pytest on the project?
=> Remove a debug printing statement

.bandit, README.md, circle.yml, crime_data/app.py, crime_data/commands.py, crime_data/common/base.py, requirements/dev.txt
=> Add bandit to CI, fix a few false positives

system-security-plan.yml
This is the initial system security plan doc.
=> Added initial SSP

crime_data/app.py, crime_data/common/base.py, crime_data/common/credentials.py, manifest.yml, newrelic.ini, requirements/prod.txt, tests/unit/test_credentials.py
Fixes #182 
I also used this opportunity to extract the functionality for looking up credentials in a VCAP_SERVICES to a new helper method. I think this will be enough to get it working, but I am not entirely sure...
=> Setup New Relic monitoring for the API

crime_data/app.py, tests/functional/test_status.py
Fixes #277 
This will be used for uptime checks by New Relic.
=> Add an unauthenticated /status endpoint to the API

circle.yml
I think this will fix the issue where bandit was not being run on PRs but only master, seen in #275
=> Move bandit execution into different test stage on CI

.about.yml
Fixes #188 
Feel free to suggest edits for anything else in here. This is a document that can also evolve as the project does.
=> Add an about.yml to the project

requirements/dev.txt
Just cleaning up some outdated dev dependencies in Gemnasium
=> Upgrading some old dev PIP requirements

setup.cfg, tests/functional/test_arrests.py, tests/functional/test_arson.py, tests/functional/test_incidents.py
- PR for @catherinedevlin 's update on the sample data.
=> Bigger test data set

crime_data/common/marshmallow_schemas.py, crime_data/resources/codes.py, tests/functional/test_codes.py
Just adding a few more things that were missing
=> Add a few more tables to the codes endpoint

crime_data/app.py, crime_data/common/cdemodels.py, crime_data/common/marshmallow_schemas.py, crime_data/resources/offenses.py, sql/functions.sql, sql/setup-denorm.sh, tests/functional/test_offenses.py
Added API's:
```
/offenses/count/national/<string:variable>?year=<REQUIRED>
/offenses/count/states/<int:state_id>/<string:variable>?year=<REQUIRED>
/offenses/count/counties/<int:county_id>/<string:variable>?year=<REQUIRED>
```
=> Added offenses/count APIs

crime_data/common/marshmallow_schemas.py, crime_data/resources/arson.py, crime_data/resources/geo.py, crime_data/resources/incidents.py, crime_data/resources/meta.py
=> Fix it, so Swagger JSON doesn't default to "body" parameters

crime_data/common/base.py, tests/unit/test_cderesource.py
=> Try to urldecode the API key if it doesn't normally match

dba/after_load/mat-views/offense.sql, dba/after_load/mat-views/victim-offenses.sql, dba/after_load/mat-views/victim.sql, sql/mat-views/aggregate-views.sql, sql/mat-views/offense-offenses.sql
(1) Fixed Victims views to correctly feed the right columns into the victims_counts views.
(2) Fixed all of the aggregate views to have year be an int
Fixes #343
=> Fix issues with view generation.

.codeclimate.yml, crime_data/app.py, crime_data/common/cdemodels.py, crime_data/common/marshmallow_schemas.py, crime_data/common/newmodels.py, crime_data/resources/geo.py, dba/after_load.sh, dba/after_load/create_reta_summary.sql, dba/after_load/participation_table.sql, tests/functional/test_geo.py, tests/unit/test_cdemodels.py
Fixes #310
This will allow us to add participation rates to the `/geo` endpoint when done
=> Materialized views for participation rates

crime_data/app.py, crime_data/common/base.py, crime_data/common/cdemodels.py, crime_data/common/marshmallow_schemas.py, crime_data/common/models.py, crime_data/common/newmodels.py, crime_data/resources/agencies.py, dba/after_load/participation_table.sql, tests/unit/test_cdemodels.py
This can be merged now.
Fixes #367 
Returns a paginated array of records like this
``` json
{
"agency_name": "Ashland",
"agency_ori": "OH0030100",
"reported": 1,
"state_abbr": "OH",
"state_name": "Ohio",
"year": 1960
},
```
Can be called with filters like `?state_postal_abbr=OH` or `?year=2014` to limit to specific records. Also can be called with `output=csv&per_page=1000000` to get a CSV download.
=> Agency Participation Endpoint

dba/after_load/participation_table.sql, tests/unit/test_cdemodels.py
=> Fixing some broken tests

circle.yml, runtime.txt
=> Upgrade from Python 3.4.4 to 3.4.5

crime_data/app.py, crime_data/extensions.py, crime_data/resources/agencies.py, crime_data/resources/arrests.py, crime_data/resources/arson.py, crime_data/resources/cargo_theft.py, crime_data/resources/codes.py, crime_data/resources/geo.py, crime_data/resources/incidents.py, crime_data/resources/meta.py, crime_data/resources/offenders.py, crime_data/resources/offenses.py, crime_data/resources/victims.py, requirements/prod.txt
=> Add cache-control headers to Flask responses

crime_data/common/marshmallow_schemas.py, crime_data/common/newmodels.py, crime_data/resources/participation.py, dba/after_load/participation_table.sql, tests/unit/test_newmodels.py
Fixes #420 
Fixes #419
This will require the participation_table.sql to be run on production again, @cacraig
=> Participation should do national rollup

CHANGELOG.md
@harrisj and @cacraig - I just requested reviews on this from you both. I think I got everything from the last sprint but I wanted to make sure I didn't miss something. If its all good, please don't merge. I'll tag the commit, push the tag, and then merge the PR myself.
I used this [compare/b457ff3...master](https://github.com/18F/crime-data-api/compare/b457ff3a755351920cfddb874da29b1c3074d553...master) to compile the list.
=> Update CHANGELOG for 2017-03-29 release

crime_data/app.py, crime_data/common/marshmallow_schemas.py, crime_data/common/models.py, crime_data/common/newmodels.py, crime_data/resources/agencies.py, crime_data/static/swagger.json, dba/after_load.sh, dba/after_load/denorm-agencies.sql, tests/functional/test_agencies.py, tests/unit/test_newmodels.py
=> Create cde_agencies table

crime_data/app.py
=> Remove a few deprecated API endpoints

crime_data/resources/incidents.py
This is my bad. Year is an optional parameter. - Just a quick fix.
=> Hotfix - year parameter should be checked for.

crime_data/common/newmodels.py, crime_data/resources/incidents.py
Sorry, got another hotfix. Year shouldn't be required on County level requests. Fixes failing calls when year not provided.
=> Reta agency api - Bug fixes.

crime_data/static/swagger.json, tests/conftest.py
=> Change Swagger to point to api.usa.gov instead

crime_data/common/base.py, crime_data/common/newmodels.py, crime_data/resources/incidents.py
Fix for pagination + out of memory issue fix. Makes pagination work + fixes issue with large requests being loaded into memory.
=> Fix for pagination + out of memory issue fix.

crime_data/resources/estimates.py
=> Order estimates by year

CHANGELOG.md
@cacraig and @harrisj could you let me know if I missed anything?
It seemed like a lot of the PRs were bits of features so I just chose the largest PRs I could find. I also left out some stuff like adding data for tests, `.cfignore` and reorganizing the manifests but am happy to include if you think it should be in there
=> Add changelog entries for v2017-05-12

README.md, crime_data/static/swagger.json, tests/test_swagger.py
It doesn't appear to be supported anymore.
Fixes #505
=> Remove the aggregate_many param from Swagger

crime_data/app.py, requirements/prod.txt
=> Add a CORS header to app responses

crime_data/app.py, crime_data/common/marshmallow_schemas.py, crime_data/common/newmodels.py, crime_data/resources/incidents.py, crime_data/static/swagger.json, dba/after_load/create_reta_agency_summary.sql, tests/functional/test_agencies.py
Fixes #518
This still needs some tests, but it creates an offense-grouped equivalent of the agency_sums_view
=> Create an offense-grouped version of agency_sums table

crime_data/common/marshmallow_schemas.py, crime_data/common/newmodels.py, crime_data/resources/incidents.py, crime_data/static/swagger.json, dba/after_load/create_reta_agency_summary.sql, tests/functional/test_agencies.py
Fixes part of #529, but will need to be run on production
=> Add classification grouping for agency offenses

crime_data/common/cdemodels.py, tests/functional/test_participation.py
=> State postal abbr lookup should be case-insensitive

.gitignore, Procfile, bin/start.sh, requirements/prod.txt
This PR is to switch over the production API server to use gunicorn instead of the flask debug server.
=> Switching production to use gunicorn

CHANGELOG.md
@harrisj and @cacraig If you could give this a glance over, I promise to follow through on the release this time!
=> Update changelog for v2017-06-08

crime_data/common/newmodels.py, crime_data/static/swagger.json, dba/after_load/participation_table.sql
=> Add participating population for NIBRS to participation_rate

crime_data/app.py, crime_data/resources/arson.py, crime_data/resources/cargo_theft.py, crime_data/resources/hate_crime.py, crime_data/resources/human_traffic.py, crime_data/resources/incidents.py, crime_data/resources/offenders.py, crime_data/resources/offenses.py, crime_data/resources/participation.py, crime_data/resources/victims.py
=> Set Surrogate-Control Header to cache responses for an hour

README.md
=> Use the cf connect-to-service plugin for DB tunnels

crime_data/common/cdemodels.py, crime_data/resources/participation.py, crime_data/static/swagger.json, dba/after_load.sh, dba/after_load/cde_states.sql, dba/after_load/denorm-agencies.sql, dba/after_load/participation_table.sql, tests/functional/test_geo.py, tests/unit/test_cde_ref_state.py
Fixes #515 
This has not been applied to production yet and I really don't want to mess with the DB today, but I am putting this here.
=> CDE States Table

CHANGELOG.md
@harrisj and @cacraig how does this look to you?
=> Update changelog for 2017-06-30

README.md, dba/after_load/ext/update_agency_names.sql
Fixes #601 and updates the README to reflect it
=> Add a simple SQL script for updating agency names from CSV

CHANGELOG.md
@cacraig can I get a review of this to see if I missed anything? If not, feel free to merge
=> Update changelog for v2017-07-20

crime_data/common/newmodels.py
THIS NEEDS REVIEWED HEAVILY -- FIRST API COMMIT. 
I did test locally but is was a struggle.
=> Adds 2016 year filtering to queries

CHANGELOG.md
=> Include release date in changelog

crime_data/common/base.py
=> Removes compile() as recommended from VAL scan report we recieved

crime_data/common/newmodels.py, crime_data/resources/incidents.py
This is just a temporary fix. A better approach will be to define constants in such a way to be easily adjusted or dynamically loaded from the database.
Fixes https://github.com/18F/crime-data-explorer/issues/328
=> Fix a DB query that was forcing agency results to be < 2016

dba/after_load/asr_summaries.sql
Fixes #668. Merge when the data files have been validated.
=> Fix some issues with race counts in the ASR crosstabs

dba/nibrs_update/README.md, dba/nibrs_update/create.sql, dba/nibrs_update/index.sql, dba/nibrs_update/update.sql, dba/nibrs_update/upload.sql
These were requested by @jpwentz
=> Add some scripts I had used for loading NIBRS data

dba/nibrs_bulk_downloads/tasks.py
Added a type of task that checks if an upstream file is missing or has a new modification time. If so, it deletes all local targets and sets complete() to false
=> Add Luigi task to force rebuild if outdated

dba/specialized_reports/setup.sql, dba/specialized_reports/violence_against_women.sql
Here are the various SQL steps to build all the intermediate tables for violence_against_women and the SQL to build that table
=> Specialized reports
